name: PR Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  preview:
    uses: kristjanjansen/mf-infra/.github/workflows/pr-preview.yml@main
    with:
      service_name: mf-translations
      port: 4000
    secrets:
      infra_token: ${{ secrets.INFRA_TOKEN }}
